---

-  hosts:  all
   become: true
   tasks:

   -  name:  install few aps
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state:  latest
        update_cache:  yes
